# Generated by Django 3.2.5 on 2021-07-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Year',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
