# Generated by Django 3.2.5 on 2021-07-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210709_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='addres',
            new_name='address',
        ),
    ]
