# Generated by Django 3.2.5 on 2021-07-10 00:25

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
